time: 2017-07-03 10:16:49.367875Z
tags: worker-0
test: setUpClass (tests.ScenarioNoError)
time: 2017-07-03 10:16:49.367875Z
failure: setUpClass (tests.ScenarioNoError) [ multipart
Content-Type: text/x-traceback;charset=utf8,language=python
traceback
331
Traceback (most recent call last):
  File "/root/workspace/cloudbase-init-ci/argus/scenarios/base.py", line 144, in setUpClass
    cls.prepare_instance()
  File "/root/workspace/cloudbase-init-ci/argus/scenarios/base.py", line 162, in prepare_instance
    cls.prepare_recipe()
  File "/root/workspace/cloudbase-init-ci/argus/scenarios/cloud/base.py", line 31, in prepare_recipe
    return cls.recipe.prepare(service_type=cls.service_type)
  File "/root/workspace/cloudbase-init-ci/argus/recipes/cloud/base.py", line 192, in prepare
    self.prepare_cbinit_config(service_type)
  File "/root/workspace/cloudbase-init-ci/argus/recipes/cloud/windows.py", line 846, in prepare_cbinit_config
    self._cbinit_conf.set_conf_value(name="matadata_service",
AttributeError: 'NoneType' object has no attribute 'set_conf_value'
0
]
tags: -worker-0
