time: 2017-07-03 15:29:34.489731Z
tags: worker-0
test: setUpClass (tests.ScenarioNoError)
time: 2017-07-03 15:29:34.489731Z
failure: setUpClass (tests.ScenarioNoError) [ multipart
Content-Type: text/x-traceback;charset=utf8,language=python
traceback
689
Traceback (most recent call last):
  File "/root/workspace/cloudbase-init-ci/argus/scenarios/base.py", line 144, in setUpClass
    cls.prepare_instance()
  File "/root/workspace/cloudbase-init-ci/argus/scenarios/base.py", line 162, in prepare_instance
    cls.prepare_recipe()
  File "/root/workspace/cloudbase-init-ci/argus/scenarios/cloud/base.py", line 31, in prepare_recipe
    return cls.recipe.prepare(service_type=cls.service_type)
  File "/root/workspace/cloudbase-init-ci/argus/recipes/cloud/base.py", line 184, in prepare
    self.wait_for_boot_completion()
  File "/root/workspace/cloudbase-init-ci/argus/recipes/cloud/windows.py", line 51, in wait_for_boot_completion
    self._backend.remote_client.manager.wait_boot_completion()
  File "/root/workspace/cloudbase-init-ci/argus/util.py", line 265, in __get__
    instance.__dict__[self.name] = result = self.func(instance)
  File "/root/workspace/cloudbase-init-ci/argus/backends/windows.py", line 38, in get_remote_client
    transport_protocol=protocol)
  File "/root/workspace/cloudbase-init-ci/argus/client/windows.py", line 85, in __init__
    self.manager = get_windows_action_manager(self)
  File "/root/workspace/cloudbase-init-ci/argus/action_manager/windows.py", line 855, in get_windows_action_manager
    wait_boot_completion(client, username)
  File "/root/workspace/cloudbase-init-ci/argus/action_manager/windows.py", line 44, in wait_boot_completion
    command_type=util.POWERSHELL)
  File "/root/workspace/cloudbase-init-ci/argus/client/windows.py", line 331, in run_command_until_condition
    .format(cmd))
argus.exceptions.ArgusTimeoutError: Command "echo 'CiAdmin'" failed too many times.
0
]
tags: -worker-0
